include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    sort_constructors_first: true
    prefer_single_quotes: true
    flutter_style_todos: true
    library_private_types_in_public_api: false
    use_super_parameters: true
