name: flutter-tests

on: [ push ]

jobs:
  analysis:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
          architecture: x64
      - name: Verify formatting
        run: dart format . --set-exit-if-changed
      - name: Install dependencies
        run: flutter pub get
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Analyze code
        run: dart analyze .